version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - bodyclose
    - dupl
    - errcheck
    - funlen
    - goconst
    - gocyclo
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - prealloc
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    errcheck:
      check-type-assertions: false
    funlen:
      lines: 80
      statements: 40
    govet:
      disable:
        - asmdecl
        - assign
      enable-all: true
    misspell:
      locale: UK
      ignore-rules:
        - initialized
  exclusions:
    generated: lax
    rules:
      - linters:
          - staticcheck
        text: '^SA1019: .* is deprecated:'
      - linters:
          - dupl
          - funlen
          - gosec
          - lll
          - nlreturn
          - unused
        path: _test\.go
      - linters:
          - errcheck
        path: _test\.go
        text: ^Error return value is not checked$
      - path: (.+)\.go$
        text: declaration of "(err|ctx)" shadows declaration at
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
